Added getting help section
google/Xee pull request #195
Opened 2024-12-13 19:58 UTC by tylere

Adds a short Getting Help section to the repo's README file.

2024-12-16 18:09 UTC, naschmitz requested changes

2024-12-17 20:54 UTC, tylere commented
Fixes #197

2025-01-02 18:18 UTC, tylere commented
Ping for @naschmitz to confirm the requested change and to review the issue templates.

2025-01-07 15:56 UTC, naschmitz approved these changes

2025-01-07 19:22 UTC, merged