feat: Allow users to configure the internal thread pool (#11)
google/Xee pull request #54
Opened 2023-10-08 04:20 UTC by alhridoy

This PR introduces a new feature that allows users to configure the internal thread pool used in the `_raw_indexing_method` function of the `EarthEngineBackendArray` class. 

A new optional parameter `executor_kwargs` has been added to the function. This parameter is a dictionary that can be used to pass configuration options to the `ThreadPoolExecutor`. If `executor_kwargs` is not provided, an empty dictionary is used, preserving the current behavior.

This feature provides users with more flexibility and control over the execution of the function, especially in scenarios where specific thread pool configurations are needed.

Changes:
- Added `executor_kwargs` parameter to `_raw_indexing_method` function in `xee/ext.py`.

Please review and let me know if any changes are required.

2023-10-08 16:47 UTC, alxmrs requested changes
Thanks for your contribution, @alhridoy! I have some initial feedback. 

A couple more high-level notes: 
- Make sure that users can set this from `open_dataset()`. To accomplish this, the new keyword arg needs to be accepted in `EarthEngineBackendEntrypoint()`.
- Please update our integration tests to prove that everything is working.

2023-10-08 16:47 UTC, alxmrs commented on configurable-thread-pool
> +Branch 'configurable-thread-pool' set up to track remote branch 'main' from 'origin'.
Please remove this file.

2023-10-08 16:47 UTC, alxmrs commented on xee/ext.py
> +      self, key: tuple[Union[int, slice], ...], executor_kwargs: Optional[dict] = None
This extra argument is named well, but I think it should be set in the constructor.

2023-10-08 16:47 UTC, alxmrs commented on xee/ext.py
> +      executor_kwargs = {}
Let's do this bit of logic in the constructor, too.

2023-10-08 16:47 UTC, alxmrs commented on xee/ext.py
> +    # Pass executor_kwargs to ThreadPoolExecutor
Comment is a bit too verbose for my taste.

2023-10-12 05:09 UTC, alhridoy commented
Hi @alxmrs when i run the test file, this error pops up.

`Could not import runpy module
Traceback (most recent call last):
  File "<frozen runpy>", line 15, in <module>
  File "<frozen importlib.util>", line 16, in <module>
  File "/Users/hridoy/Desktop/open_source/Xee/xee/types.py", line 16, in <module>
    from typing import Union, TypedDict
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 27, in <module>
    import contextlib
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 7, in <module>
    from functools import wraps
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/Users/hridoy/Desktop/open_source/Xee/xee/types.py)` 
I renamed the types.py to type.py then I run the test again, it runs but no output is shown in the terminal. any guidance to run the ext_integration_test.py file?

2023-10-12 05:39 UTC, alhridoy commented
@alxmrs Thanks for your guidance. Would you check if these changes are working properly? if not,  Please let me necessary the changes I need to make. Thanks

2023-10-12 18:23 UTC, alxmrs commented on xee/ext.py
> +  def __init__(self, executor_kwargs=None):
There already is a constructor.

2023-10-12 18:23 UTC, alxmrs commented on xee/ext_integration_test.py
> +  def test_open_dataset_with_executor_kwargs(self):
Thanks for the test!

2023-10-12 18:23 UTC, alxmrs commented
Please fix the merge conflicts in this branch.

2023-10-12 21:37 UTC, alhridoy commented
Hi @alxmrs . Thanks for the feedback. ,I added  a new parameter executor_kwargs has been added to the __init__ method also resolved merge conflict.

2023-10-13 19:40 UTC, alxmrs reviewed
Definitely looking better. Here are a few more additional suggestions.

2023-10-13 19:40 UTC, alxmrs commented on xee/ext.py
> +      self.executor_kwargs = executor_kwargs
```suggestion
    if executor_kwargs is None:
      executor_kwargs = {}
    self.executor_kwargs = executor_kwargs
```

2023-10-13 19:40 UTC, alxmrs commented on xee/ext.py
> +      self, key: tuple[Union[int, slice], ...]
Please remove extra space (to minimize the diff).

2023-10-13 19:40 UTC, alxmrs commented on xee/ext.py
> +      self.executor_kwargs = executor_kwargs
Please initialize this at the top or bottom of the `__init__`.

2023-10-13 19:40 UTC, alxmrs commented on xee/ext.py
> +      executor_kwargs: Optional[dict] = None,
In addition to adding it to the arguments, please update the docstring.

2023-10-15 22:53 UTC, alhridoy commented
Hi @alxmrs , Would you check the new commits address your comments? If there is still any issue  I would be happy to work on that.

2023-10-15 23:08 UTC, alxmrs commented
It feels like you are using a bot to make this patch. I'll be happy to work with you to add this feature. First, please do a self review before I make any additional reviews.

2023-11-09 00:32 UTC, alhridoy commented
Thanks! Please give me couple of weeks.

2024-01-22 10:28 UTC, closed without merging